spring:
  redis:
    host: 192.168.100.120
    password: redis
  datasource:
#    serverTimezone=GMT%2B8使用东八区时间
    url: jdbc:mysql://192.168.100.120:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
