server:
  ssl:
    key-store: /usr/local/exam/ssl/tomcat.jks
    key-password: Qwer!@#$%

spring:
  redis:
    host: 127.0.0.1
    password: redis
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123


