server:
  ssl:
    key-store: /usr/local/exam/ssl/tomcat.jks
    key-password: Qwer!@#$%

spring:
  redis:
    host: 192.168.100.200
  datasource:
    url: jdbc:mysql://192.168.100.200:3306/exam
    username: root
    password: root
