spring:
  redis:
#    host: 192.168.100.200
    host: 127.0.0.1
    password: redis
  datasource:
    #  serverTimezone=GMT%2B8使用东八区时间
    url: jdbc:mysql://192.168.100.200:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    #    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
