spring:
  redis:
    host: 101.132.110.182
    password: 123456
  datasource:
#    serverTimezone=GMT%2B8使用东八区时间
    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
